# Generated by Django 6.0.7 on 2026-08-20 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AgentDevice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="How this machine is known to you -- typically the server's hostname or the office it sits in.", max_length=255, unique=True, verbose_name='Name')),
                ('description', models.TextField(blank=True, help_text='Anything worth remembering about this machine.', verbose_name='Description')),
                ('pairing_code', models.CharField(blank=True, editable=False, max_length=9, null=True, unique=True, verbose_name='Pairing code')),
                ('pairing_code_expires_at', models.DateTimeField(blank=True, editable=False, null=True, verbose_name='Pairing code expires at')),
                ('token_hash', models.CharField(blank=True, editable=False, max_length=64, null=True, unique=True, verbose_name='Device token hash')),
                ('paired_at', models.DateTimeField(blank=True, editable=False, null=True, verbose_name='Paired at')),
                ('last_seen_at', models.DateTimeField(blank=True, editable=False, null=True, verbose_name='Last seen at')),
                ('revoked_at', models.DateTimeField(blank=True, editable=False, null=True, verbose_name='Revoked at')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
            ],
            options={
                'verbose_name': 'Agent Device',
                'verbose_name_plural': 'Agent Devices',
                'ordering': ['name'],
            },
        ),
    ]
