# Generated by Django 6.0.7 on 2026-08-20 15:46

import adl_agent_plugin.validators
import django.core.validators
import django.db.models.deletion
import modelcluster.fields
import timezone_field.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adl_agent_plugin', '0001_initial'),
        ('core', '0051_alter_networkconnection_ingest_timeout_seconds'),
    ]

    operations = [
        migrations.CreateModel(
            name='AgentStationLink',
            fields=[
                ('stationlink_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.stationlink')),
                ('local_folder_path', models.CharField(help_text="Folder on the machine where the vendor software writes this station's files, e.g. C:\\VendorData\\Station1", max_length=500, verbose_name='Local Folder Path')),
                ('file_pattern', models.CharField(blank=True, help_text="Glob the filenames must match, e.g. 'Station1_*.dat'. Not used by Direct Fetch, which builds the names instead.", max_length=255, verbose_name='File Pattern')),
                ('dir_structured_by_date', models.BooleanField(default=False, help_text='Check if the files sit under dated sub-folders of the path above, in the form [YYYY]/[MM]/[DD]/[HH].', verbose_name='Folder structured by date?')),
                ('date_granularity', models.CharField(blank=True, choices=[('year', 'Year'), ('month', 'Month'), ('day', 'Day'), ('hour', 'Hour')], help_text='How far down the dated folder tree the files sit.', max_length=20, null=True, verbose_name='Date Granularity')),
                ('month_dir_format', models.CharField(blank=True, choices=[('m', "Month, 2 digits with leading zeros. '01' to '12'"), ('n', "Month without leading zeros. '1' to '12'"), ('M', "Month, textual, 3 letters. 'Jan'"), ('b', "Month, textual, 3 letters, lowercase. 'jan'"), ('F', "Month, textual, full. 'January'"), ('f', "Month, textual, full, lowercase. 'january'")], default='m', max_length=5, null=True, verbose_name='Month folder format')),
                ('listing_strategy', models.CharField(choices=[('enumerate', 'Enumerate — scan the folder and match files by pattern'), ('direct_fetch', 'Direct Fetch — construct expected filenames, never scan')], default='enumerate', help_text="How the agent finds this station's files. Enumerate suits almost every folder. Direct Fetch is for folders so large that listing them is itself the problem, and needs filenames the agent can construct.", max_length=40, verbose_name='File Listing Strategy')),
                ('direct_fetch_prefix', models.CharField(blank=True, help_text="Everything in the filename before the datetime. For 'STATION_001_20260219122000.txt' that is 'STATION_001_'.", max_length=100, null=True, verbose_name='File Prefix')),
                ('direct_fetch_interval_minutes', models.PositiveIntegerField(blank=True, help_text='Minutes between consecutive files, e.g. 10.', null=True, verbose_name='File Interval (minutes)')),
                ('direct_fetch_datetime_format', models.CharField(blank=True, help_text="How the datetime is written in the filename, e.g. yyyyMMddHHmmss for '20260219122000'.", max_length=50, null=True, verbose_name='File Datetime Format')),
                ('direct_fetch_datetime_timezone', timezone_field.fields.TimeZoneField(default='UTC', help_text='Timezone of the datetime in the filename. Check with the vendor whether it is local time or UTC.', verbose_name='File Datetime Timezone')),
                ('direct_fetch_file_extension', models.CharField(blank=True, default='.txt', help_text="Extension including the dot, e.g. '.txt'.", max_length=10, null=True, verbose_name='File Extension')),
                ('stability_window_seconds', models.PositiveIntegerField(default=60, help_text='A file written more recently than this is left alone until the next cycle, so a file still being written is never shipped half-finished.', verbose_name='Stability Window (seconds)')),
                ('start_date', models.DateTimeField(blank=True, help_text='Collection never starts before this date. On a fresh install it is the start of the backfill; moving it forward makes the agent stop offering anything older.', null=True, validators=[adl_agent_plugin.validators.validate_start_date], verbose_name='Collection Start Date')),
            ],
            options={
                'verbose_name': 'Agent Station Link',
                'verbose_name_plural': 'Agent Station Links',
            },
            bases=('core.stationlink',),
        ),
        migrations.AddField(
            model_name='agentdevice',
            name='check_interval_minutes',
            field=models.PositiveIntegerField(default=5, help_text='How often this machine scans its folders and offers what it finds to ADL.', validators=[django.core.validators.MinValueValidator(1)], verbose_name='Check interval (minutes)'),
        ),
        migrations.AddField(
            model_name='agentdevice',
            name='config_version',
            field=models.PositiveBigIntegerField(default=1, editable=False, verbose_name='Configuration version'),
        ),
        migrations.CreateModel(
            name='AgentConnection',
            fields=[
                ('networkconnection_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.networkconnection')),
                ('device', models.ForeignKey(help_text="The machine that sends this connection's files.", on_delete=django.db.models.deletion.PROTECT, related_name='connections', to='adl_agent_plugin.agentdevice', verbose_name='Agent Device')),
            ],
            options={
                'verbose_name': 'Agent Connection',
                'verbose_name_plural': 'Agent Connections',
            },
            bases=('core.networkconnection',),
        ),
        migrations.CreateModel(
            name='AgentConnectionVariableMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('file_variable_name', models.CharField(max_length=255, verbose_name='File Variable Name')),
                ('adl_parameter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.dataparameter', verbose_name='ADL Parameter')),
                ('file_variable_unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.unit', verbose_name='File Variable Unit')),
                ('network_connection', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='variable_mappings', to='adl_agent_plugin.agentconnection')),
            ],
            options={
                'verbose_name': 'Agent Connection Variable Mapping',
                'verbose_name_plural': 'Agent Connection Variable Mappings',
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AgentStationLinkVariableMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('file_variable_name', models.CharField(max_length=255, verbose_name='File Variable Name')),
                ('adl_parameter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.dataparameter', verbose_name='ADL Parameter')),
                ('file_variable_unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.unit', verbose_name='File Variable Unit')),
                ('station_link', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='variable_mappings', to='adl_agent_plugin.agentstationlink')),
            ],
            options={
                'verbose_name': 'Agent Station Link Variable Mapping',
                'verbose_name_plural': 'Agent Station Link Variable Mappings',
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
    ]
