# Generated by Django 6.0.7 on 2026-08-20 16:21

import adl_agent_plugin.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adl_agent_plugin', '0002_agentstationlink_agentdevice_check_interval_minutes_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AgentStationDataFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.CharField(max_length=255, verbose_name='File Name')),
                ('size', models.PositiveBigIntegerField(help_text='Size of the file as ADL received it.', verbose_name='Size (bytes)')),
                ('mtime', models.DateTimeField(help_text="When the vendor software last wrote this file, as reported by the machine. What the agent windows its folder scan on -- not an observation time, which only the file's contents can say.", verbose_name='Last Modified')),
                ('content_hash', models.CharField(blank=True, help_text="sha-256 of the file's bytes, verified on arrival.", max_length=64, null=True, verbose_name='Content Hash')),
                ('file', models.FileField(blank=True, upload_to=adl_agent_plugin.models.agent_data_file_path, verbose_name='File')),
                ('received_at', models.DateTimeField(blank=True, null=True, verbose_name='Received At')),
                ('status', models.CharField(choices=[('received', 'Received — waiting to be processed'), ('processed', 'Processed'), ('failed', 'Failed to process')], default='received', max_length=20, verbose_name='Status')),
                ('processed_at', models.DateTimeField(blank=True, help_text="When this file's records were last persisted by ADL.", null=True, verbose_name='Processed At')),
                ('values_saved', models.PositiveIntegerField(blank=True, help_text='Observation values ADL kept from this file the last time it was processed. 0 means it decoded but nothing was kept — typically a variable-mapping or ingestion-window mismatch.', null=True, verbose_name='Values Saved')),
                ('last_error', models.TextField(blank=True, default='', verbose_name='Last Error')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('station_link', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='data_files', to='adl_agent_plugin.agentstationlink', verbose_name='Agent Station Link')),
            ],
            options={
                'verbose_name': 'Agent Station Data File',
                'verbose_name_plural': 'Agent Station Data Files',
                'indexes': [models.Index(fields=['station_link', 'status'], name='idx_agentfile_link_status'), models.Index(fields=['station_link', 'mtime'], name='idx_agentfile_link_mtime')],
                'constraints': [models.UniqueConstraint(fields=('station_link', 'file_name'), name='unique_agent_file_per_station_link')],
            },
        ),
    ]
