# Generated by Django 6.0.7 on 2026-08-20 17:05

import adl_ftp_plugin.utils
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adl_agent_plugin', '0003_agentstationdatafile'),
        # The migration that creates StandardCSVConfig, rather than the FTP
        # plugin's latest: this only needs the table it points at to exist,
        # and pinning the tip would refuse to run beside an older -- but
        # entirely sufficient -- FTP plugin.
        ('adl_ftp_plugin', '0018_standardcsvconfig_networkftp_csv_config'),
    ]

    operations = [
        migrations.AddField(
            model_name='agentconnection',
            name='csv_config',
            field=models.ForeignKey(blank=True, help_text='Required by decoders that read a configurable CSV; ignored by decoders that know their own format.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='adl_ftp_plugin.standardcsvconfig', verbose_name='CSV Configuration'),
        ),
        migrations.AddField(
            model_name='agentconnection',
            name='decoder',
            field=models.CharField(choices=adl_ftp_plugin.utils.get_ftp_decoder_choices, default='', help_text="How this vendor's files are read. The list is every decoder installed on this ADL instance.", max_length=255, verbose_name='Decoder'),
            preserve_default=False,
        ),
    ]
