# Generated by Django 6.0.7 on 2026-08-20 17:50

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adl_agent_plugin', '0004_agentconnection_csv_config_agentconnection_decoder'),
    ]

    operations = [
        migrations.AddField(
            model_name='agentconnection',
            name='file_retention_days',
            field=models.PositiveIntegerField(blank=True, default=90, help_text="Delete a file's staged bytes this many days after ADL processed it. What ADL knows about the file is kept, so the machine is never asked for it again; a file that failed to process keeps its bytes whatever this says. Leave empty to keep every byte.", null=True, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Staged File Retention (days)'),
        ),
    ]
