# Generated by Django 6.0.7 on 2026-08-20 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adl_agent_plugin', '0005_agentconnection_file_retention_days'),
    ]

    operations = [
        migrations.AddField(
            model_name='agentstationdatafile',
            name='reoffer_requested_at',
            field=models.DateTimeField(blank=True, help_text='When ADL last asked the machine to send this file again.', null=True, verbose_name='Re-send Requested At'),
        ),
    ]
