# Generated by Django 6.0.7 on 2026-08-20 19:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adl_agent_plugin', '0006_agentstationdatafile_reoffer_requested_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='agentdevice',
            name='agent_version',
            field=models.CharField(blank=True, default='', editable=False, max_length=100, verbose_name='Agent version'),
        ),
        migrations.AddField(
            model_name='agentdevice',
            name='clock_skew_seconds',
            field=models.IntegerField(blank=True, editable=False, null=True, verbose_name='Clock skew (seconds)'),
        ),
        migrations.AddField(
            model_name='agentdevice',
            name='heartbeat_details',
            field=models.JSONField(blank=True, default=dict, editable=False, verbose_name='Heartbeat details'),
        ),
        migrations.AddField(
            model_name='agentdevice',
            name='last_cycle_completed_at',
            field=models.DateTimeField(blank=True, editable=False, null=True, verbose_name='Last cycle completed at'),
        ),
        migrations.AddField(
            model_name='agentdevice',
            name='last_heartbeat_at',
            field=models.DateTimeField(blank=True, editable=False, null=True, verbose_name='Last heartbeat at'),
        ),
        migrations.AddField(
            model_name='agentdevice',
            name='liveness_since',
            field=models.DateTimeField(blank=True, editable=False, null=True, verbose_name='Liveness since'),
        ),
        migrations.AddField(
            model_name='agentdevice',
            name='liveness_state',
            field=models.CharField(choices=[('online', 'Online'), ('degraded', 'Degraded'), ('offline', 'Offline'), ('cycle_stuck', 'Cycle stuck'), ('unknown', 'Unknown')], default='unknown', editable=False, max_length=20, verbose_name='Liveness'),
        ),
        migrations.AddField(
            model_name='agentdevice',
            name='os_version',
            field=models.CharField(blank=True, default='', editable=False, max_length=255, verbose_name='Operating system'),
        ),
        migrations.AddField(
            model_name='agentdevice',
            name='pinned_version',
            field=models.CharField(blank=True, default='', help_text='Hold this machine on one agent version instead of letting it follow the update feed. Leave empty to keep it current.', max_length=100, verbose_name='Pinned version'),
        ),
        migrations.CreateModel(
            name='AgentDeviceStateTransition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('at', models.DateTimeField(verbose_name='At')),
                ('from_state', models.CharField(blank=True, choices=[('online', 'Online'), ('degraded', 'Degraded'), ('offline', 'Offline'), ('cycle_stuck', 'Cycle stuck'), ('unknown', 'Unknown')], default='', max_length=20, verbose_name='From')),
                ('to_state', models.CharField(choices=[('online', 'Online'), ('degraded', 'Degraded'), ('offline', 'Offline'), ('cycle_stuck', 'Cycle stuck'), ('unknown', 'Unknown')], max_length=20, verbose_name='To')),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='state_transitions', to='adl_agent_plugin.agentdevice', verbose_name='Agent Device')),
            ],
            options={
                'verbose_name': 'Agent Device State Transition',
                'verbose_name_plural': 'Agent Device State Transitions',
                'ordering': ['-at', '-pk'],
                'indexes': [models.Index(fields=['device', 'at'], name='agent_dev_trans_at_idx')],
            },
        ),
    ]
