# Generated by Django 6.0.7 on 2026-08-22 12:53

import adl_agent_plugin.models
import django.core.validators
import django.db.models.deletion
import modelcluster.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adl_agent_plugin', '0007_agentdevice_agent_version_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AgentRelease',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.CharField(help_text='Three numbers, as the agent reports itself: 1.2.0.', max_length=32, unique=True, validators=[django.core.validators.RegexValidator('^\\d+\\.\\d+\\.\\d+$', message='An agent version is three numbers separated by dots, such as 1.2.0.')], verbose_name='Version')),
                ('notes', models.TextField(blank=True, help_text='What changed. Shown here only; agents never read it.', verbose_name='Release notes')),
                ('is_published', models.BooleanField(default=False, help_text='Until this is ticked, no machine is offered this release. A release mirrored from upstream arrives unpublished so that this instance decides when its own fleet moves.', verbose_name='Published')),
                ('released_at', models.DateTimeField(blank=True, help_text="When this version was built. Upstream's date, when mirrored.", null=True, verbose_name='Released at')),
                ('source', models.CharField(choices=[('uploaded', 'Uploaded here'), ('mirrored', 'Mirrored from upstream')], default='uploaded', editable=False, max_length=20, verbose_name='Source')),
                ('upstream_url', models.URLField(blank=True, default='', editable=False, help_text='Where this release was mirrored from, if it was.', verbose_name='Upstream URL')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
            ],
            options={
                'verbose_name': 'Agent Release',
                'verbose_name_plural': 'Agent Releases',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AgentReleaseArtifact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('msi', 'Windows Installer package — service tier upgrade'), ('velopack_full', 'Velopack release — per-user tier upgrade'), ('velopack_setup', 'Velopack installer — per-user first install')], max_length=32, verbose_name='Kind')),
                ('file', models.FileField(help_text='The package itself. Served to agents from this instance.', upload_to=adl_agent_plugin.models.agent_release_file_path, verbose_name='File')),
                ('sha256', models.CharField(blank=True, default='', editable=False, help_text='Computed from the stored bytes. What an agent checks against.', max_length=64, verbose_name='SHA-256')),
                ('size', models.PositiveBigIntegerField(blank=True, editable=False, null=True, verbose_name='Size (bytes)')),
                ('expected_sha256', models.CharField(blank=True, default='', help_text='Optional. Paste the digest the build published and this package will be refused unless the uploaded bytes match it.', max_length=64, verbose_name='Expected SHA-256')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('release', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='artifacts', to='adl_agent_plugin.agentrelease', verbose_name='Release')),
            ],
            options={
                'verbose_name': 'Agent Release Package',
                'verbose_name_plural': 'Agent Release Packages',
                'constraints': [models.UniqueConstraint(fields=('release', 'kind'), name='unique_agent_release_artifact_kind')],
            },
        ),
    ]
