# Generated by Django 6.0.7 on 2026-08-27 19:38

import django.db.models.deletion
import timescale.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adl_agent_plugin', '0012_agentdevice_last_file_received_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='agentdevice',
            name='log_level',
            field=models.CharField(blank=True, choices=[('Trace', 'Trace — everything, for a few minutes'), ('Debug', 'Debug — a support session'), ('Information', 'Information — the usual'), ('Warning', 'Warning — only what went wrong'), ('Error', 'Error — only what failed')], default='', help_text='How much this machine writes to its own log. Leave blank to use whatever the machine itself is set to. Debug is for a support session and can be left on -- the log has a fixed size ceiling, so what it costs is how far back the log reaches, not disk.', max_length=20, verbose_name='Log level'),
        ),
        migrations.CreateModel(
            name='AgentCyclePass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', timescale.db.models.fields.TimescaleDateTimeField(interval='1 day')),
                ('unit', models.CharField(blank=True, help_text='The folder this pass is named by.', max_length=500, verbose_name='Unit')),
                ('trigger', models.CharField(blank=True, choices=[('scheduled', 'Scheduled'), ('reconciliation', 'Reconciliation sweep'), ('collect', 'Collect now')], max_length=20, verbose_name='Trigger')),
                ('completed', models.BooleanField(default=False, help_text='False when the pass was cut short, and then the reason says why.', verbose_name='Completed')),
                ('stopped', models.TextField(blank=True, default='', verbose_name='Stopped Because')),
                ('duration_ms', models.PositiveIntegerField(blank=True, null=True, verbose_name='Duration (ms)')),
                ('folders_walked', models.PositiveIntegerField(blank=True, null=True, verbose_name='Folders Walked')),
                ('scanned', models.PositiveIntegerField(blank=True, help_text="Files in the folder matching this station's pattern.", null=True, verbose_name='Scanned')),
                ('held', models.PositiveIntegerField(blank=True, help_text='Files left alone because they were still being written.', null=True, verbose_name='Held')),
                ('offered', models.PositiveIntegerField(blank=True, null=True, verbose_name='Offered')),
                ('wanted', models.PositiveIntegerField(blank=True, help_text='Files ADL asked for out of what was offered.', null=True, verbose_name='Wanted')),
                ('uploaded', models.PositiveIntegerField(blank=True, null=True, verbose_name='Uploaded')),
                ('failed', models.PositiveIntegerField(blank=True, null=True, verbose_name='Failed')),
                ('backlog', models.PositiveIntegerField(blank=True, help_text='What the machine held that ADL did not.', null=True, verbose_name='Backlog')),
                ('error', models.TextField(blank=True, default='', help_text='What went wrong for this station, including the reason a station the scan turned away was turned away.', verbose_name='Error')),
                ('missing_files', models.JSONField(blank=True, default=list, verbose_name='Files That Did Not Arrive')),
                ('received_at', models.DateTimeField(verbose_name='Received At')),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cycle_passes', to='adl_agent_plugin.agentdevice', verbose_name='Device')),
                ('station_link', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cycle_passes', to='adl_agent_plugin.agentstationlink', verbose_name='Agent Station Link')),
            ],
            options={
                'verbose_name': 'Agent Cycle Pass',
                'verbose_name_plural': 'Agent Cycle Passes',
                'ordering': ['-time'],
                'get_latest_by': 'time',
                'indexes': [models.Index(fields=['station_link', 'time'], name='idx_agentpass_link_time'), models.Index(fields=['device', 'time'], name='idx_agentpass_device_time'), models.Index(condition=models.Q(('completed', False), ('failed__gt', 0), _connector='OR'), fields=['time'], name='idx_agentpass_wrong')],
            },
        ),
    ]
